### ISSUE TITLE
Add inline component documentation using JSDoc (built into Svelte)

### ISSUE THREAD

**Issue by benaltair** [prismicio/prismic-svelte#1]
As this library is developed, it would be great to start adding inline documentation which can be used to provide intellisense through that Svelte Language Server.

For example, here's a component with basic documentation:
```svelte
<script lang="ts">
	import { RichText } from 'prismic-dom';

	import type { RichTextField as RichTextFieldType } from '@prismicio/types';
	import type { TitleField as TitleFieldType } from '@prismicio/types';
        /** A Prismic field. */
	export let field: TitleFieldType | RichTextFieldType;
	export let separator: string = undefined;
</script>
<!--
	@component
	Produces plain text from Prismic Rich Text or Title fields.
	
-->
{@html RichText.asText(field, separator)}

```

https://svelte.dev/faq#how-do-i-document-my-components

This shows to the user like this: 
![image](https://user-images.githubusercontent.com/17771229/136610109-cae06e0c-7399-4473-a28a-ae3a823554c6.png)

**Comment by samlfair** [comment]
@benaltair Yep, we're planning to document everything with TSDocs 🙂

**Comment by benaltair** [comment]
Perfect - after looking through the other Prismic libraries I see this wasn't necessary 😄 
Looking forward to seeing things coming together. I'll keep an eye on the docs to see if there are any improvements that would be worth a PR, as they get added

**Comment by samlfair** [comment]
@benaltair We've been adding components to the package and using TSDoc as we go, so I'm going to close this issue 👍
